const axios = require("axios");

const oldjokes = [
  `Which bear is the most condescending? A pan-duh!`,
  `What kind of noise does a witch’s vehicle make? Brrrroooom, brrroooom.`,
  `What’s brown and sticky? A stick.`,
  `Two guys walked into a bar. The third guy ducked.`,
  `How do you get a country girl’s attention? A tractor.`,
  `Why are elevator jokes so classic and good? They work on many levels.`,
  `What do you call a pudgy psychic? A four-chin teller.`,
  `What did the police officer say to his belly-button? You’re under a vest.`,
  `What do you call it when a group of apes start a company? Monkey business.`,
  `My wife asked me to stop singing “Wonderwall” to her. I said maybe –`,
  `What kind of drink can be bitter and sweet? Reali-tea.`,
  `What do you call a naughty lamb dressed up like a skeleton for Halloween? Baaad to the bone.`,
  `Want to know why nurses like red crayons? Sometimes they have to draw blood.`,
  `What would the Terminator be called in his retirement? The Exterminator.`,
  `What did Tennessee? The same thing as Arkansas.`,
  `My wife asked me to go get 6 cans of Sprite from the grocery store. I realized when I got home that I had picked 7 up.`,
  `Why do bees have sticky hair? Because they use a honeycomb.`,
  `Why do some couples go to the gym? Because they want their relationship to work out.`,
  `What do you call an angry musician flipping someone off? A song bird.`,
  `What’s the most detail-oriented ocean? The Pacific.`,
  `Did you hear about the kidnapping at school? It’s fine, he woke up.`,
  `How can you tell it’s a dogwood tree? By the bark.`,
  `My boss told me to have a good day, so I went home.`,
  `Why did the man fall down the well? Because he couldn’t see that well.`,
  `When does a joke become a “dad joke?” When it becomes apparent.`,
  `Why is Peter Pan always flying? Because he Neverlands.`,
  `Which state has the most streets? Rhode Island.`,
  `What do you call 26 letters that went for a swim? Alphawetical.`,
  `What’s the name of a very polite, European body of water? Merci.`,
  `Why was the color green notoriously single? It was always so jaded.`,
  `I used to hate facial hair, but then it grew on me.`,
  `I want to make a brief joke, but it’s a little cheesy.`,
  `Why did the coach go to the bank? To get his quarterback.`,
  `How do celebrities stay cool? They have many fans.`,
  `Sundays are always a little sad, but the day before is a sadder day.`,
  `5/4 of people admit they’re bad at fractions.`,
  `Why did the bedding hide their relationship? They just wanted something pillow-key!`,
  `You’re American when you go into a bathroom and when you come out, but what are you while you’re in the bathroom? European.`,
  `I’ve been thinking about taking up meditation. I figure it’s better than sitting around doing nothing.`,
  `Dogs can’t operate MRI machines. But catscan.`,
  `What did the flowers do when the bride walked down the aisle? They rose.`,
  `It takes guts to be an organ donor.`,
  `What does “Rockin’ Robin” do when she’s bored? Tweet.`,
  `I lost my job at the bank on my first day. A woman asked me to check her balance, so I pushed her over.`,
  `How do you row a canoe filled with puppies? Bring out the doggy paddle.`,
  `Singing in the shower is fun until you get soap in your mouth. Then it becomes a soap opera.`,
  `Why were the utensils stuck together? They were spooning.`,
  `What’s a crafty dancer’s favorite hobby? Cutting a rug.`,
  `How does a penguin build his house? Igloos it together.`,
  `What kind of music do chiropractor’s like? Hip pop.`,
  `What kind of shoes does a lazy person wear? Loafers.`,
  `Why is cold water so insecure? Because it’s never called hot.`,
  `I was going to tell a time-traveling joke, but you guys didn’t like it.`,
  `Shouldn’t the “roof” of your mouth actually be called the ceiling?`,
  `Stop looking for the perfect match…use a lighter.`,
  `I told my doctor I heard buzzing, but he said it’s just a bug going around.`,
  `What kind of car does a sheep like to drive? A lamborghini.`,
  `What did the accountant say while auditing a document? This is taxing.`,
  `What did the two pieces of bread say on their wedding day? It was loaf at first sight.`,
  `If the early bird gets the worm, I’ll sleep in until there’s pancakes.`,
  `Why do melons have weddings? Because they cantaloupe.`,
  `I signed up for a marathon, but how will I know if it’s the real deal or just a run through?`,
  `When you have a bladder infection, urine trouble.`,
  `What did the drummer call his twin daughters? Anna One, Anna Two!`,
  `What did the juicer say to the orange during self-quarantine? Can’t wait to squeeze you!`,
  `What do you call a toothless bear? A gummy bear!`,
  `Want to hear a joke about construction? I’m still working on it.`,
  `Someone told me that I should write a book. I said, “That’s a novel concept.”`,
  `Two goldfish are in a tank. One says to the other, “Do you know how to drive this thing?”`,
  `What’s Forrest Gump’s password? 1forrest1`,
  `I tell dad jokes, but I don’t have any kids. I’m a faux pa.`,
  `What does a nosey pepper do? It gets jalapeño business.`,
  `If a child refuses to nap, are they guilty of resisting a rest?`,
  `Why do dads feel the need to tell such bad jokes? They just want to help you become a groan up.`,
  `I know a lot of jokes about retired people, but none of them work.`,
  `Why are spiders so smart? They can find everything on the web.`,
  `RIP boiled water—you will be mist.`,
  `What do you call two octopuses that look the same? Itenticle.`,
  `What has one head, one foot, and four legs? A bed.`,
  `Sore throats are a pain in the neck.`,
  `What does a house wear? Address.`,
  `Why did the scarecrow win an award? He was out standing in his field.`,
  `What’s red and smells like blue paint? Red paint.`,
  `My son asked me to put his shoes on, but I don’t think they’ll fit me.`,
  `I’ve been bored recently, so I decided to take up fencing. The neighbors keep demanding that I put it back.`,
  `What do you call an unpredictable camera? A loose Canon.`,
  `I didn’t get a haircut, I got them all cut.`,
  `Which U.S. state is known for its especially small soft drinks? Minnesota.`,
  `What do sprinters eat before a race? Nothing—they fast.`,
  `What did one Dorito farmer say to the other? “Cool Ranch!”`,
  `Why couldn’t the bicycle stand up by itself? It was two-tired.`,
  `I’m so good at sleeping, I can do it with my eyes closed.`,
  `People are usually shocked that I have a Police record. But I love their greatest hits!`,
  `I told my girlfriend she drew on her eyebrows too high. She seemed surprised.`,
  `What do you call a fibbing cat? A lion.`,
  `Why shouldn’t you write with a broken pencil? Because it’s pointless.`,
  `I like telling Dad jokes…sometimes he laughs.`,
  `How do you weigh a millennial? In Instagrams.`,
  `The wedding was so beautiful, even the cake was in tiers.`,
  `What’s the most patriotic sport? Flag football.`,
  `Today, my son asked "Can I have a book mark?" and I burst into tears. 11 years old and he still doesn't know my name is Brian.`,
  `My wife is really mad at the fact that I have no sense of direction. So I packed up my stuff and right.`,
  `How do you make holy water? You boil the hell out of it.`,
  `Did you know the first French fries weren't actually cooked in France? They were cooked in Greece.`,
];

const jokes = [
  `To whoever stole my copy of Microsoft Office, I will find you. You have my Word!`,
  `I'll call you later. Don't call me later, call me Dad!`,
  `How do celebrities stay cool? They have many fans.`,
  `What's Forrest Gump's Facebook password? 1forest1.`,
  `What do you call it when Batman skips church? Christian Bale.`,
  `What time did the man go to the dentist? Tooth hurt-y.`,
  `Did you hear about the man who fell into an upholstery machine? He's fully recovered.`,
  `Why didn't the melons get married? Because they cantaloupe.`,
  `What kind of egg did the evil chicken lay? A deviled egg.`,
  `Why did the coach go to the bank? To get his quarter back.`,
  `Why does Snoop Dogg always carry an umbrella? Fo' Drizzle.`,
  `What did the fisherman say to the magician? Pick a cod, any cod.`,
  `What do you call a fake noodle? An impasta.`,
  `Which is faster, hot or cold? Hot, because you can catch a cold.`,
  `How do you organize a space party? You planet.`,
  `Did you know that milk is the fastest liquid on earth? It's pasteurized before you even see it.`,
  `Why are skeletons so calm? Because nothing gets under their skin.`,
  `What did one ocean say to the other ocean? Nothing, they just waved.`,
  `What does a baby computer call his father? Data.`,
  `Did you hear about the power outlet who got into a fight with a power cord? He thought he could socket to him.`,
  `Why are elevator jokes so good? They work on so many levels.`,
  `Why can't a leopard hide? Because he's always spotted.`,
  `How do moths swim? Using the butterfly stroke.`,
  `How many tickles does it take to make an octopus laugh? 10 tickles.`,
  `Do you know the story about the chicken that crossed the border? Me neither, I couldn't follow it.`,
  `I made a pencil with two erasers. It was pointless.`,
  `How do you make a Kleenex dance? Put a little boogie in it!`,
  `What do you get from a pampered cow? Spoiled milk!`,
  `What do you call an illegally parked frog? Toad.`,
  `Where do baby cats learn to swim? The kitty pool.`,
  `Why are spiders so smart? They can find everything on the web.`,
  `How can a leopard change his spots? By moving.`,
];

(async () => {
  jokes.forEach(async (joke) => {
    await axios("http://localhost:8080/jokes", {
      method: "POST",
      data: {
        joke,
      },
    });
  });
})();
